package api

import (
	"net/http"

	_ "github.com/fercho/school-tracking/services/auth/docs/api" // docs is generated by Swag CLI, you have to import it.
	"github.com/fercho/school-tracking/services/auth/internal/infrastructure/api/controllers"
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	httpSwagger "github.com/swaggo/http-swagger/v2"
)

// NewRouter creates and configures the chi router with middleware and auth routes.
func NewRouter(authCtrl *controllers.AuthController) *chi.Mux {
	r := chi.NewRouter()

	r.Use(middleware.RequestID)
	r.Use(middleware.RealIP)
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)

	// Swagger UI
	r.Get("/swagger/*", httpSwagger.Handler(
		httpSwagger.URL("/swagger/doc.json"), // The url pointing to API definition
	))

	r.Get("/health", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("auth is healthy"))
	})

	r.Route("/api/v1/auth", func(r chi.Router) {
		r.Post("/register", authCtrl.Register)
		r.Post("/login", authCtrl.Login)
		r.Post("/refresh", authCtrl.RefreshToken)
	})

	return r
}
