// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/fercho/school-tracking/services/auth/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockJWTManager is an autogenerated mock type for the JWTManager type
type MockJWTManager struct {
	mock.Mock
}

type MockJWTManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJWTManager) EXPECT() *MockJWTManager_Expecter {
	return &MockJWTManager_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields: user
func (_m *MockJWTManager) Generate(user *domain.User) (*domain.TokenPair, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 *domain.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.User) (*domain.TokenPair, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(*domain.User) *domain.TokenPair); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TokenPair)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJWTManager_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockJWTManager_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - user *domain.User
func (_e *MockJWTManager_Expecter) Generate(user interface{}) *MockJWTManager_Generate_Call {
	return &MockJWTManager_Generate_Call{Call: _e.mock.On("Generate", user)}
}

func (_c *MockJWTManager_Generate_Call) Run(run func(user *domain.User)) *MockJWTManager_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.User))
	})
	return _c
}

func (_c *MockJWTManager_Generate_Call) Return(_a0 *domain.TokenPair, _a1 error) *MockJWTManager_Generate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJWTManager_Generate_Call) RunAndReturn(run func(*domain.User) (*domain.TokenPair, error)) *MockJWTManager_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAccessToken provides a mock function with given fields: token
func (_m *MockJWTManager) ValidateAccessToken(token string) (*domain.Claims, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 *domain.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Claims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Claims); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJWTManager_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type MockJWTManager_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - token string
func (_e *MockJWTManager_Expecter) ValidateAccessToken(token interface{}) *MockJWTManager_ValidateAccessToken_Call {
	return &MockJWTManager_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", token)}
}

func (_c *MockJWTManager_ValidateAccessToken_Call) Run(run func(token string)) *MockJWTManager_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockJWTManager_ValidateAccessToken_Call) Return(_a0 *domain.Claims, _a1 error) *MockJWTManager_ValidateAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJWTManager_ValidateAccessToken_Call) RunAndReturn(run func(string) (*domain.Claims, error)) *MockJWTManager_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRefreshToken provides a mock function with given fields: token
func (_m *MockJWTManager) ValidateRefreshToken(token string) (*domain.Claims, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRefreshToken")
	}

	var r0 *domain.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Claims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Claims); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJWTManager_ValidateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRefreshToken'
type MockJWTManager_ValidateRefreshToken_Call struct {
	*mock.Call
}

// ValidateRefreshToken is a helper method to define mock.On call
//   - token string
func (_e *MockJWTManager_Expecter) ValidateRefreshToken(token interface{}) *MockJWTManager_ValidateRefreshToken_Call {
	return &MockJWTManager_ValidateRefreshToken_Call{Call: _e.mock.On("ValidateRefreshToken", token)}
}

func (_c *MockJWTManager_ValidateRefreshToken_Call) Run(run func(token string)) *MockJWTManager_ValidateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockJWTManager_ValidateRefreshToken_Call) Return(_a0 *domain.Claims, _a1 error) *MockJWTManager_ValidateRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJWTManager_ValidateRefreshToken_Call) RunAndReturn(run func(string) (*domain.Claims, error)) *MockJWTManager_ValidateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJWTManager creates a new instance of MockJWTManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJWTManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJWTManager {
	mock := &MockJWTManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
