basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: API documentation for the auth service of the School Tracking System.
  title: Auth Service API
  version: "1.0"
paths: {}
swagger: "2.0"
